use_frameworks!

target 'MusicNotationKit_Example' do
  pod 'MusicNotationKit', :path => '../'

  target 'MusicNotationKit_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
